export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';


export const MEDICIN_GET = 'MEDICIN_GET';
export const MEDICIN_ADD = 'MEDICIN_ADD';
export const MEDICIN_UPDATE = 'MEDICIN_UPDATE';
export const MEDICIN_DELETE = 'MEDICIN_DELETE';


export const DOCTOR_GET = 'DOCTOR_GET';
export const DOCTOR_ADD = 'DOCTOR_ADD';
export const DOCTOR_UPDATE = 'DOCTOR_UPDATE';
export const DOCTOR_DELETE = 'DOCTOR_DELETE';

export const THEME_TOGGLE = 'THEME_TOGGLE';